local wire = require("twilic.core.wire")
local twilic = require("twilic")
describe("security limits", function()
  it("accepts an empty shape without table growth loops", function()
    local value = twilic.decode(string.char(0xa1, 0xd6, 0, 0))
    assert.equal(1, #value.arr)
  end)
  it("rejects cumulative output and invalid lengths", function()
    local r = wire.new_reader("\0")
    r:claim_output(100)
    assert.has_error(function() r:claim_output(100) end)
    assert.has_error(function() r:read_exact(-1) end)
  end)
  it("rejects deep structures", function()
    assert.has_error(function() twilic.decode(string.rep(string.char(0xa1), 70) .. string.char(0xc0)) end)
  end)
end)
