"""Twilic Python — native Pure Python port of twilic-go."""

from __future__ import annotations

from ._version import __version__
from .errors import (
    ErrInvalidData,
    ErrInvalidKind,
    ErrInvalidTag,
    ErrStatelessRetryRequired,
    ErrUnexpectedEOF,
    ErrUnknownReference,
    ErrUTF8,
    TwilicError,
    TwilicErrorKind,
)
from .model import (
    BaseRef,
    BaseSnapshotMessage,
    Column,
    ColumnBatchMessage,
    ControlMessage,
    ControlOpcode,
    ControlOpcodePromoteStringFieldToEnum,
    ControlOpcodeRegisterKeys,
    ControlOpcodeRegisterShape,
    ControlOpcodeRegisterStrings,
    ControlOpcodeResetState,
    ControlOpcodeResetTables,
    ControlStreamCodec,
    ControlStreamCodecBitpack,
    ControlStreamCodecFse,
    ControlStreamCodecHuffman,
    ControlStreamCodecPlain,
    ControlStreamCodecRle,
    ControlStreamMessage,
    ElementType,
    ElementTypeBinary,
    ElementTypeBool,
    ElementTypeF64,
    ElementTypeI64,
    ElementTypeString,
    ElementTypeU64,
    ElementTypeValue,
    ExtMessage,
    KeyRef,
    MapEntry,
    Message,
    MessageKind,
    MessageKindArray,
    MessageKindBaseSnapshot,
    MessageKindColumnBatch,
    MessageKindControl,
    MessageKindControlStream,
    MessageKindExt,
    MessageKindMap,
    MessageKindRowBatch,
    MessageKindScalar,
    MessageKindSchemaObject,
    MessageKindShapedObject,
    MessageKindStatePatch,
    MessageKindTemplateBatch,
    MessageKindTypedVector,
    MessageMapEntry,
    NullStrategy,
    NullStrategyAllPresentElided,
    NullStrategyInvertedPresenceBitmap,
    NullStrategyNone,
    NullStrategyPresenceBitmap,
    PatchOpcode,
    PatchOpcodeAppendVector,
    PatchOpcodeDeleteField,
    PatchOpcodeInsertField,
    PatchOpcodeKeep,
    PatchOpcodePrefixDelta,
    PatchOpcodeReplaceScalar,
    PatchOpcodeReplaceVector,
    PatchOpcodeStringRef,
    PatchOpcodeTruncateVector,
    PatchOperation,
    PromoteEnumControl,
    RegisterShapeControl,
    RowBatchMessage,
    Schema,
    SchemaField,
    SchemaObjectMessage,
    ShapedObjectMessage,
    StatePatchMessage,
    StringMode,
    StringModeEmpty,
    StringModeInlineEnum,
    StringModeLiteral,
    StringModePrefixDelta,
    StringModeRef,
    StringValue,
    TemplateBatchMessage,
    TemplateDescriptor,
    TypedVector,
    TypedVectorData,
    Value,
    ValueArray,
    ValueBinary,
    ValueBool,
    ValueF64,
    ValueI64,
    ValueKind,
    ValueMap,
    ValueNull,
    ValueString,
    ValueU64,
    VectorCodec,
    VectorCodecDeltaBitpack,
    VectorCodecDeltaDeltaBitpack,
    VectorCodecDeltaForBitpack,
    VectorCodecDictionary,
    VectorCodecDirectBitpack,
    VectorCodecForBitpack,
    VectorCodecPatchedFor,
    VectorCodecPlain,
    VectorCodecPrefixDelta,
    VectorCodecRle,
    VectorCodecSimple8b,
    VectorCodecStringRef,
    VectorCodecXorFloat,
    base_ref_id,
    base_ref_previous,
    entry,
    equal,
    key_ref_id,
    key_ref_literal,
    new_array,
    new_binary,
    new_bool,
    new_f64,
    new_i64,
    new_map,
    new_null,
    new_string,
    new_u64,
)
from .protocol import (
    SessionEncoder,
    TwilicCodec,
    new_session_encoder,
    new_twilic_codec,
    reset_encode_shape_observation,
    twilic_codec_with_options,
)
from .session import (
    DictionaryFallback,
    DictionaryFallbackFailFast,
    DictionaryFallbackStatelessRetry,
    DictionaryProfile,
    SessionOptions,
    SessionState,
    UnknownReferencePolicy,
    UnknownReferencePolicyFailFast,
    UnknownReferencePolicyStatelessRetry,
    default_session_options,
)
from .v2 import decode_v2 as decode
from .v2 import encode_v2 as encode


def encode_with_schema(schema: Schema, value: Value) -> bytes:
    enc = new_session_encoder(default_session_options())
    return enc.encode_with_schema(schema, value)


def encode_batch(values: list[Value]) -> bytes:
    enc = new_session_encoder(default_session_options())
    return enc.encode_batch(values)


# Go export.go compatible aliases (PascalCase)
NewNull = new_null
NewBool = new_bool
NewI64 = new_i64
NewU64 = new_u64
NewF64 = new_f64
NewString = new_string
NewBinary = new_binary
NewArray = new_array
Entry = entry
NewMap = new_map
Equal = equal
KeyRefLiteral = key_ref_literal
KeyRefID = key_ref_id
BaseRefPrevious = base_ref_previous
BaseRefID = base_ref_id
DefaultSessionOptions = default_session_options
NewTwilicCodec = new_twilic_codec
TwilicCodecWithOptions = twilic_codec_with_options
NewSessionEncoder = new_session_encoder
ResetEncodeShapeObservation = reset_encode_shape_observation
Encode = encode
Decode = decode
EncodeWithSchema = encode_with_schema
EncodeBatch = encode_batch


__all__ = [
    "__version__",
    "BaseRef",
    "BaseSnapshotMessage",
    "Column",
    "ColumnBatchMessage",
    "ControlMessage",
    "ControlOpcode",
    "ControlOpcodePromoteStringFieldToEnum",
    "ControlOpcodeRegisterKeys",
    "ControlOpcodeRegisterShape",
    "ControlOpcodeRegisterStrings",
    "ControlOpcodeResetState",
    "ControlOpcodeResetTables",
    "ControlStreamCodec",
    "ControlStreamCodecBitpack",
    "ControlStreamCodecFse",
    "ControlStreamCodecHuffman",
    "ControlStreamCodecPlain",
    "ControlStreamCodecRle",
    "ControlStreamMessage",
    "DictionaryFallback",
    "DictionaryFallbackFailFast",
    "DictionaryFallbackStatelessRetry",
    "DictionaryProfile",
    "ElementType",
    "ElementTypeBinary",
    "ElementTypeBool",
    "ElementTypeF64",
    "ElementTypeI64",
    "ElementTypeString",
    "ElementTypeU64",
    "ElementTypeValue",
    "ErrInvalidData",
    "ErrInvalidKind",
    "ErrInvalidTag",
    "ErrStatelessRetryRequired",
    "ErrUnexpectedEOF",
    "ErrUTF8",
    "ErrUnknownReference",
    "ExtMessage",
    "KeyRef",
    "MapEntry",
    "Message",
    "MessageKind",
    "MessageKindArray",
    "MessageKindBaseSnapshot",
    "MessageKindColumnBatch",
    "MessageKindControl",
    "MessageKindControlStream",
    "MessageKindExt",
    "MessageKindMap",
    "MessageKindRowBatch",
    "MessageKindScalar",
    "MessageKindSchemaObject",
    "MessageKindShapedObject",
    "MessageKindStatePatch",
    "MessageKindTemplateBatch",
    "MessageKindTypedVector",
    "MessageMapEntry",
    "NullStrategy",
    "NullStrategyAllPresentElided",
    "NullStrategyInvertedPresenceBitmap",
    "NullStrategyNone",
    "NullStrategyPresenceBitmap",
    "PatchOpcode",
    "PatchOpcodeAppendVector",
    "PatchOpcodeDeleteField",
    "PatchOpcodeInsertField",
    "PatchOpcodeKeep",
    "PatchOpcodePrefixDelta",
    "PatchOpcodeReplaceScalar",
    "PatchOpcodeReplaceVector",
    "PatchOpcodeStringRef",
    "PatchOpcodeTruncateVector",
    "PatchOperation",
    "PromoteEnumControl",
    "RegisterShapeControl",
    "RowBatchMessage",
    "Schema",
    "SchemaField",
    "SchemaObjectMessage",
    "SessionEncoder",
    "SessionOptions",
    "SessionState",
    "ShapedObjectMessage",
    "StatePatchMessage",
    "StringMode",
    "StringModeEmpty",
    "StringModeInlineEnum",
    "StringModeLiteral",
    "StringModePrefixDelta",
    "StringModeRef",
    "StringValue",
    "TemplateBatchMessage",
    "TemplateDescriptor",
    "TwilicCodec",
    "TwilicError",
    "TwilicErrorKind",
    "TypedVector",
    "TypedVectorData",
    "UnknownReferencePolicy",
    "UnknownReferencePolicyFailFast",
    "UnknownReferencePolicyStatelessRetry",
    "Value",
    "ValueArray",
    "ValueBinary",
    "ValueBool",
    "ValueF64",
    "ValueI64",
    "ValueKind",
    "ValueMap",
    "ValueNull",
    "ValueString",
    "ValueU64",
    "VectorCodec",
    "VectorCodecDeltaBitpack",
    "VectorCodecDeltaDeltaBitpack",
    "VectorCodecDeltaForBitpack",
    "VectorCodecDictionary",
    "VectorCodecDirectBitpack",
    "VectorCodecForBitpack",
    "VectorCodecPatchedFor",
    "VectorCodecPlain",
    "VectorCodecPrefixDelta",
    "VectorCodecRle",
    "VectorCodecSimple8b",
    "VectorCodecStringRef",
    "VectorCodecXorFloat",
    "base_ref_id",
    "base_ref_previous",
    "decode",
    "default_session_options",
    "encode",
    "encode_batch",
    "encode_with_schema",
    "entry",
    "equal",
    "key_ref_id",
    "key_ref_literal",
    "new_array",
    "new_binary",
    "new_bool",
    "new_f64",
    "new_i64",
    "new_map",
    "new_null",
    "new_session_encoder",
    "new_string",
    "new_twilic_codec",
    "new_u64",
    "reset_encode_shape_observation",
    "twilic_codec_with_options",
]
