<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Twilic</RootNamespace>
    <AssemblyName>Twilic</AssemblyName>
    <Version>0.1.0</Version>
    <Description>Native C# Twilic v2 SDK</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
